services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - APP_PORT=5000
      - MYSQL_IP=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=BANCO_DADOS_IT_TALENT
    depends_on:
      - db

  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: BANCO_DADOS_IT_TALENT
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
