version: '3.8'
services:
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - MYSQL_IP=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=BANCO_DADOS_IT_TALENT
    depends_on:
      - db

  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: BANCO_DADOS_IT_TALENT
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
